name: Test the Action

on:
  push:
    branches: ["main"]

jobs:
  test-rsmetacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run RsMetaCheck locally
        # "uses: ./" tells GitHub to use the action
        # defined in the root of the CURRENT repository.
        uses: ./
        with:
          # test with default input (current repository)
          verbose: "true"

      - name: Verify outputs generated
        run: |
          ls -la
          ls -la pitfalls_outputs
